app = "portfolio-back-qw9pyq"
primary_region = "cdg"

[env]
    JAVA_OPTS = "-Xmx512m"

[[services]]
    internal_port = 8080
    protocol = "tcp"

[[services.ports]]
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "30s"
