CREATE TABLE app_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version  INTEGER NOT NULL,
    password VARCHAR(60),
    username VARCHAR(30),
    CONSTRAINT ukspsnwr241e9k9c8p5xl4k45ih UNIQUE (username)
);

CREATE TABLE projects
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL,
    category         VARCHAR(255) NOT NULL,
    file_name        VARCHAR(255),
    stored_file_name VARCHAR(255),
    demo_link        VARCHAR(500),
    git_link         VARCHAR(500),
    id_video         VARCHAR(11),
    start_date       DATE,
    status           VARCHAR(255) NOT NULL,
    summary          VARCHAR(550) NOT NULL,
    title            VARCHAR(100) NOT NULL,
    CONSTRAINT projects_category_check CHECK (
        category IN ('PERSONAL_PROJECT', 'PROFESSIONAL_PROJECT')
        ),
    CONSTRAINT projects_status_check CHECK (
        status IN ('IN_PROGRESS', 'MAINTAINED', 'ARCHIVED', 'CANCELLED')
        ),
    CONSTRAINT uktjhqwalyna982dhwdnx5ksuwv UNIQUE (title)
);

CREATE TABLE tag_types
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                INTEGER     NOT NULL,
    background_color_dark  VARCHAR(7)  NOT NULL,
    background_color_light VARCHAR(7)  NOT NULL,
    name                   VARCHAR(40) NOT NULL,
    text_color_dark        VARCHAR(7)  NOT NULL,
    text_color_light       VARCHAR(7)  NOT NULL,
    CONSTRAINT uk94rcrvkaxqi6dwnqc05ggwxey UNIQUE (name)
);

CREATE TABLE tags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER     NOT NULL,
    name        VARCHAR(40) NOT NULL,
    tag_type_id BIGINT      NOT NULL,
    CONSTRAINT ukt48xdq560gs3gap9g7jg36kgc UNIQUE (name),
    CONSTRAINT fkiw9yusf4yv2v7t0qbpd02qtra FOREIGN KEY (tag_type_id) REFERENCES tag_types (id)
);

CREATE TABLE settings
(
    setting_key   VARCHAR(50) PRIMARY KEY,
    is_protected  BOOLEAN      NOT NULL,
    setting_value VARCHAR(255) NOT NULL,
    version       INTEGER      NOT NULL
);

CREATE TABLE project_features
(
    project_id BIGINT NOT NULL,
    features   VARCHAR(255),
    CONSTRAINT fk58okhnl0y399a1gl4kmgl44xt FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE project_files
(
    project_id       BIGINT NOT NULL,
    file_name        VARCHAR(255),
    stored_file_name VARCHAR(255),
    CONSTRAINT files_project_fk FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE project_git_links
(
    project_id BIGINT       NOT NULL,
    label      VARCHAR(60)  NOT NULL,
    link       VARCHAR(500) NOT NULL,
    CONSTRAINT fk_git_links_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT ukfd55u8yspd141scmaflygy1dk UNIQUE (label)
);

CREATE TABLE projects_tags
(
    fk_project_id BIGINT NOT NULL,
    fk_tag_id     BIGINT NOT NULL,
    CONSTRAINT fkikhr1b9sb19j8u3bo7br99yre FOREIGN KEY (fk_project_id) REFERENCES projects (id),
    CONSTRAINT fkmb5mgbynhbaiqapmf4mj4dbpe FOREIGN KEY (fk_tag_id) REFERENCES tags (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255),
    CONSTRAINT fkaf154i5th4vvgbahf8b8pa688 FOREIGN KEY (user_id) REFERENCES app_users (id)
);
